apiVersion: v1
kind: Pod
metadata:
  name: react-pod
  labels:
    app: react
spec:
  containers:
    - name: react
      image: react-image
      imagePullPolicy: Never
      ports:
        - containerPort: 80